name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [v1.11.0, latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Binary exists
        shell: bash
        run: command -v helm-docs
      - name: Binary runs
        shell: bash
        run: helm-docs --version
